// @generated - This file is generated by esquema-codegen (forked from atrium-codegen). DO NOT EDIT.
//!A collection of known record types.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq)]
#[serde(tag = "$type")]
pub enum KnownRecord {
    #[serde(rename = "xyz.statusphere.status")]
    LexiconsXyzStatusphereStatus(Box<crate::types::lexicons::xyz::statusphere::status::Record>),
    #[serde(rename = "xyz.mercato.listing")]
    LexiconsXyzMercatoListing(Box<crate::types::lexicons::xyz::mercato::listing::Record>),
    #[serde(rename = "xyz.mercato.comment")]
    LexiconsXyzMercatoComment(Box<crate::types::lexicons::xyz::mercato::comment::Record>),
}
impl From<crate::types::lexicons::xyz::statusphere::status::Record> for KnownRecord {
    fn from(record: crate::types::lexicons::xyz::statusphere::status::Record) -> Self {
        KnownRecord::LexiconsXyzStatusphereStatus(Box::new(record))
    }
}
impl From<crate::types::lexicons::xyz::statusphere::status::RecordData> for KnownRecord {
    fn from(record_data: crate::types::lexicons::xyz::statusphere::status::RecordData) -> Self {
        KnownRecord::LexiconsXyzStatusphereStatus(Box::new(record_data.into()))
    }
}
impl From<crate::types::lexicons::xyz::mercato::listing::Record> for KnownRecord {
    fn from(record: crate::types::lexicons::xyz::mercato::listing::Record) -> Self {
        KnownRecord::LexiconsXyzMercatoListing(Box::new(record))
    }
}
impl From<crate::types::lexicons::xyz::mercato::listing::RecordData> for KnownRecord {
    fn from(record_data: crate::types::lexicons::xyz::mercato::listing::RecordData) -> Self {
        KnownRecord::LexiconsXyzMercatoListing(Box::new(record_data.into()))
    }
}
impl From<crate::types::lexicons::xyz::mercato::comment::Record> for KnownRecord {
    fn from(record: crate::types::lexicons::xyz::mercato::comment::Record) -> Self {
        KnownRecord::LexiconsXyzMercatoComment(Box::new(record))
    }
}
impl From<crate::types::lexicons::xyz::mercato::comment::RecordData> for KnownRecord {
    fn from(record_data: crate::types::lexicons::xyz::mercato::comment::RecordData) -> Self {
        KnownRecord::LexiconsXyzMercatoComment(Box::new(record_data.into()))
    }
}
impl From<KnownRecord> for atrium_api::types::Unknown {
    fn from(val: KnownRecord) -> Self {
        atrium_api::types::TryIntoUnknown::try_into_unknown(&val).unwrap()
    }
}
